### ISSUE TITLE
Missing `test_bench` configuration support

### ISSUE THREAD

**Issue by shink** [pytorch/benchmark#2590]
Seems `--config` is defined but not indeed supported in the `test_bench` userbenchmark. I would like to add support for it if needed.

`args.config` is not used actually:
https://github.com/pytorch/benchmark/blob/43851fb1208fad5708af8488789754b90fe94ec6/userbenchmark/test_bench/run.py#L307-L309

cc: @xuzhao9

**Comment by shink** [comment]
Actually, I'm working on a PyTorch out-of-tree test infra project, which is using `torchbenchmark` to test out-of-tree devices and can be found at [here][1].
And we want to let each device vendor define their own configuration, might like this:

```yaml
device: "foo"
models:
  - model: BERT_pytorch
    tests: [ "eval" ]
    batch_size: 1

  - model: yolov3
    skip: true
```

[1]: https://github.com/cosdt/pytorch-integration-tests
[2]: https://github.com/pytorch/pytorch/pull/142114

<img width="935" alt="Image" src="https://github.com/user-attachments/assets/2cce2ce5-b5f3-4159-a10b-f1e9f7367be2" />
